namespace WrenSharp
{
    /// <summary>
    /// Represents an error generated by the Wren runtime.
    /// </summary>
    public class WrenError
    {
        /// <summary>
        /// The error type that was generated.
        /// </summary>
        public WrenErrorType ErrorType { get; }

        /// <summary>
        /// The module name the error occurred within.
        /// </summary>
        public string Module { get; }

        /// <summary>
        /// The line number in the script the error occurred at.
        /// </summary>
        public int Line { get; }

        /// <summary>
        /// The error message generated by Wren.
        /// </summary>
        public string Message { get; }

        internal WrenError(WrenErrorType errorType, string module, int line, string message)
        {
            ErrorType = errorType;
            Module = module;
            Line = line;
            Message = message;
        }
    }
}
